# CMake generated Testfile for 
# Source directory: C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit
# Build directory: C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_safe_log]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Debug/test_safe_log.exe")
  set_tests_properties([=[test_safe_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;7;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_safe_log]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Release/test_safe_log.exe")
  set_tests_properties([=[test_safe_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;7;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_safe_log]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/MinSizeRel/test_safe_log.exe")
  set_tests_properties([=[test_safe_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;7;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_safe_log]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/RelWithDebInfo/test_safe_log.exe")
  set_tests_properties([=[test_safe_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;7;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[test_safe_log]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_secret_manager]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Debug/test_secret_manager.exe")
  set_tests_properties([=[test_secret_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;11;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_secret_manager]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Release/test_secret_manager.exe")
  set_tests_properties([=[test_secret_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;11;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_secret_manager]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/MinSizeRel/test_secret_manager.exe")
  set_tests_properties([=[test_secret_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;11;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_secret_manager]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/RelWithDebInfo/test_secret_manager.exe")
  set_tests_properties([=[test_secret_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;11;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[test_secret_manager]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_vad]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Debug/test_vad.exe")
  set_tests_properties([=[test_vad]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;15;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_vad]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Release/test_vad.exe")
  set_tests_properties([=[test_vad]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;15;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_vad]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/MinSizeRel/test_vad.exe")
  set_tests_properties([=[test_vad]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;15;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_vad]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/RelWithDebInfo/test_vad.exe")
  set_tests_properties([=[test_vad]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;15;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[test_vad]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_signal_schema]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Debug/test_signal_schema.exe")
  set_tests_properties([=[test_signal_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;18;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_signal_schema]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Release/test_signal_schema.exe")
  set_tests_properties([=[test_signal_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;18;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_signal_schema]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/MinSizeRel/test_signal_schema.exe")
  set_tests_properties([=[test_signal_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;18;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_signal_schema]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/RelWithDebInfo/test_signal_schema.exe")
  set_tests_properties([=[test_signal_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;18;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[test_signal_schema]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_spsc_queue]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Debug/test_spsc_queue.exe")
  set_tests_properties([=[test_spsc_queue]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;22;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_spsc_queue]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/Release/test_spsc_queue.exe")
  set_tests_properties([=[test_spsc_queue]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;22;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_spsc_queue]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/MinSizeRel/test_spsc_queue.exe")
  set_tests_properties([=[test_spsc_queue]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;22;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_spsc_queue]=] "C:/Users/Home/Downloads/biona_axon/snie/build_msvc/tests/unit/RelWithDebInfo/test_spsc_queue.exe")
  set_tests_properties([=[test_spsc_queue]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;22;add_test;C:/Users/Home/Downloads/biona_axon/snie/biona/axon/tests/unit/CMakeLists.txt;0;")
else()
  add_test([=[test_spsc_queue]=] NOT_AVAILABLE)
endif()
