apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biona-production

bases:
  - ../../base

nameSuffix: ""

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biona-lab
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: biona-lab
                resources:
                  requests:
                    memory: "1Gi"
                    cpu: "500m"
                  limits:
                    memory: "4Gi"
                    cpu: "2000m"

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biona-nora-health
      spec:
        replicas: 2

images:
  - name: biona-lab
    newName: ghcr.io/biona-ai/biona-lab
  - name: biona-nora-health
    newName: ghcr.io/biona-ai/biona-nora-health
